name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install deps
      run: |
        sudo apt update &&
        sudo apt install -y git g++ make libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-net-dev libopenal-dev libvorbis-dev libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libswresample-dev liblua5.3-dev
    - name: make
      working-directory: ./src
      run: |
        pwd &&
        ls -lah Makefile &&
        make nix -j `nproc`
